### ISSUE TITLE
Error when using release v3.0.4

### ISSUE THREAD

**Issue by cpanato** [technote-space/workflow-conclusion-action#123]
## Describe the bug: バグの概要
Got an error when using release v3.0.4 and this does not happen on release v3.0.3

```
Conclusion: 
  success
  Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported
      at rng (/home/runner/work/_actions/technote-space/workflow-conclusion-action/82dd67fd29a53f18f33a99e0bbfb138318a80dcd/lib/main.js:200:13)
      at Object.v4 (/home/runner/work/_actions/technote-space/workflow-conclusion-action/82dd67fd29a53f18f33a99e0bbfb138318a80dcd/lib/main.js:646:52)
      at Object.prepareKeyValueMessage (/home/runner/work/_actions/technote-space/workflow-conclusion-action/82dd67fd29a53f18f33a99e0bbfb138318a80dcd/lib/main.js:829:46)
      at Object.setOutput (/home/runner/work/_actions/technote-space/workflow-conclusion-action/82dd67fd29a53f18f33a99e0bbfb138318a80dcd/lib/main.js:2485:75)
      at execute (/home/runner/work/_actions/technote-space/workflow-conclusion-action/82dd67fd29a53f18f33a99e0bbfb138318a80dcd/lib/main.js:88522:17)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async run (/home/runner/work/_actions/technote-space/workflow-conclusion-action/82dd67fd29a53f18f33a99e0bbfb138318a80dcd/lib/main.js:88533:5)
  Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported
0s

```

## Operating environment: バグが発生した環境
 - Version of software
 - OS: [e.g. Windows10]
 - Browser: [e.g. Chrome, Safari]
 - etc.

**Comment by cpanato** [comment]
notice that there is no release v3.0.4 yet only a test one
